### ISSUE TITLE
Little help

### ISSUE THREAD

**Issue by Jborn4christ** [mattbehnken/node-aladdin-connect-garage-door#1]
Trying to get this working. Not sure what I'm missing. Installed garage door controller plugin as well as Aladdin connect. Entered username password in node close.js etc. Still showing garage door unavailable. What am I missing.

`[6/19/2019, 11:27:38 AM] [Garage Door] Error: Error: Command failed: node state.js
internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module 'node-aladdin-connect-garage-door'
Require stack:
- C:\Users\Chambers\state.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\Users\Chambers\state.js:1:25)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\Users\\Chambers\\state.js' ]
}`

**Comment by Jborn4christ** [comment]
Now its just this:
[6/19/2019, 8:55:47 PM] [Garage Door] Error: Error: Command failed: node C:/Users/Chambers/AppData/Roaming/npm/node_modules/garage-control/state.js
C:\Users\Chambers\AppData\Roaming\npm\node_modules\node-aladdin-connect-garage-door-master\example\node_modules\node-aladdin-connect-garage-door\index.js:36
modules.export = (user, password, action, callback, deviceNumber = 0, doorNumber = 1) {
                                                                                      ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:718:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\Users\Chambers\AppData\Roaming\npm\node_modules\node-aladdin-connect-garage-door-master\example\state.js:1:25)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)

[6/19/2019, 8:55:47 PM] [Garage Door] Error: Command failed: node C:/Users/Chambers/AppData/Roaming/npm/node_modules/garage-control/state.js
C:\Users\Chambers\AppData\Roaming\npm\node_modules\node-aladdin-connect-garage-door-master\example\node_modules\node-aladdin-connect-garage-door\index.js:36
modules.export = (user, password, action, callback, deviceNumber = 0, doorNumber = 1) {
                                                                                      ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:718:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\Users\Chambers\AppData\Roaming\npm\node_modules\node-aladdin-connect-garage-door-master\example\state.js:1:25)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)

    at ChildProcess.exithandler (child_process.js:290:12)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node ' +
    'C:/Users/Chambers/AppData/Roaming/npm/node_modules/garage-control/state.js'
}
[6/19/2019, 8:56:07 PM] [Garage Door] Error: Error: Command failed: node C:/Users/Chambers/AppData/Roaming/npm/node_modules/garage-control/state.js
C:\Users\Chambers\AppData\Roaming\npm\node_modules\node-aladdin-connect-garage-door-master\example\node_modules\node-aladdin-connect-garage-door\index.js:36
modules.export = (user, password, action, callback, deviceNumber = 0, doorNumber = 1) {
                                                                                      ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:718:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\Users\Chambers\AppData\Roaming\npm\node_modules\node-aladdin-connect-garage-door-master\example\state.js:1:25)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)

[6/19/2019, 8:56:07 PM] [Garage Door] Error: Command failed: node C:/Users/Chambers/AppData/Roaming/npm/node_modules/garage-control/state.js
C:\Users\Chambers\AppData\Roaming\npm\node_modules\node-aladdin-connect-garage-door-master\example\node_modules\node-aladdin-connect-garage-door\index.js:36
modules.export = (user, password, action, callback, deviceNumber = 0, doorNumber = 1) {
                                                                                      ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:718:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\Users\Chambers\AppData\Roaming\npm\node_modules\node-aladdin-connect-garage-door-master\example\state.js:1:25)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)

    at ChildProcess.exithandler (child_process.js:290:12)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node ' +
    'C:/Users/Chambers/AppData/Roaming/npm/node_modules/garage-control/state.js'
}
[6/19/2019, 8:56:27 PM] [Garage Door] Error: Error: Command failed: node C:/Users/Chambers/AppData/Roaming/npm/node_modules/garage-control/state.js
C:\Users\Chambers\AppData\Roaming\npm\node_modules\node-aladdin-connect-garage-door-master\example\node_modules\node-aladdin-connect-garage-door\index.js:36
modules.export = (user, password, action, callback, deviceNumber = 0, doorNumber = 1) {
                                                                                      ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:718:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\Users\Chambers\AppData\Roaming\npm\node_modules\node-aladdin-connect-garage-door-master\example\state.js:1:25)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)

[6/19/2019, 8:56:27 PM] [Garage Door] Error: Command failed: node C:/Users/Chambers/AppData/Roaming/npm/node_modules/garage-control/state.js
C:\Users\Chambers\AppData\Roaming\npm\node_modules\node-aladdin-connect-garage-door-master\example\node_modules\node-aladdin-connect-garage-door\index.js:36
modules.export = (user, password, action, callback, deviceNumber = 0, doorNumber = 1) {
                                                                                      ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:718:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\Users\Chambers\AppData\Roaming\npm\node_modules\node-aladdin-connect-garage-door-master\example\state.js:1:25)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)

    at ChildProcess.exithandler (child_process.js:290:12)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node ' +
    'C:/Users/Chambers/AppData/Roaming/npm/node_modules/garage-control/state.js
